// <auto-generated />
using CallTrak_System.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CallTrak_System.Migrations
{
    [DbContext(typeof(CallTrakContext))]
    [Migration("20231109220630_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CallTrak_System.Models.CallTrak", b =>
                {
                    b.Property<int>("CallTrakID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CallTrakID"));

                    b.Property<string>("ActionContents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillingNotesContents")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescriptionContents")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevNotesContents")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CallTrakID");

                    b.ToTable("CallTraks");

                    b.HasData(
                        new
                        {
                            CallTrakID = 1,
                            ActionContents = "\"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.\"",
                            DescriptionContents = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
                        },
                        new
                        {
                            CallTrakID = 2,
                            ActionContents = "Havent done much",
                            BillingNotesContents = "$500000",
                            DescriptionContents = "Calltrak 2",
                            DevNotesContents = "some dev notes"
                        },
                        new
                        {
                            CallTrakID = 3,
                            ActionContents = "We are just starting",
                            BillingNotesContents = "Free",
                            DescriptionContents = "another Calltrack",
                            DevNotesContents = "hope this works"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
